spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      log-abandoned: true
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 1200
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 2000
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 4
        max-wait: 30
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wet
    password: wet2022
    virtual-host: dev
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: MANUAL
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: dev



sys:
  showRequestLog: true
  redisson:
    enabled: true
    type: STANDALONE
    address: 127.0.0.1:6379
    password:
    database: 0



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:/mapper/**/**.xml
