server:
  port: 8030
spring:
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    rest:
      uris: 192.168.127.129:9200
  rabbitmq:
    host: 175.178.255.153
    port: 5672
    username: wet
    password: wet2022
    virtual-host: dev
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual



sys:
  redisson:
    enabled: true
    type: STANDALONE
    address: 127.0.0.1:6379
    password:
    database: 0


