server:
  port: 8020
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 1200
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 175.178.255.153
    port: 5672
    username: wet
    password: wet2022
    virtual-host: dev
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual



sys:
  redisson:
    enabled: true
    type: STANDALONE
    address: 127.0.0.1:6379
    password:
    database: 0



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/**/**.xml
